#!/bin/sh
# This is invoked by configure_conman to generate the Mountain node
# console ssh key pair as required.
#
# Copyright 2020 Hewlett Packard Enterprise Development LP

/usr/bin/ssh-keygen -qf /etc/conman.key -N '' <<<y
